# Generated by Django 2.2.10 on 2020-02-19 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='pizza_size',
        ),
    ]
